---
name: eks
path: git::https://github.com/awslabs/idf-modules.git//modules/compute/eks?ref=main&depth=1
dataFiles:
  - filePath: data/eks_dockerimage-replication/versions/1.25.yaml
  - filePath: data/eks_dockerimage-replication/versions/default.yaml
parameters:
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: networking
        name: networking
        key: VpcId
  - name: controlplane-subnet-ids
    valueFrom:
      moduleMetadata:
        group: networking
        name: networking
        key: PrivateSubnetIds
  - name: dataplane-subnet-ids
    valueFrom:
      moduleMetadata:
        group: networking
        name: networking
        key: PrivateSubnetIds
  - name: eks-admin-role-name
    value: Admin
  - name: eks-poweruser-role-name
    value: PowerUser
  - name: eks-read-only-role-name
    value: ReadOnly
  - name: eks-version
    value: 1.25
  - name: eks-compute
    value:
      eks_nodegroup_config:
        - eks_ng_name: ng1
          eks_node_quantity: 2
          eks_node_max_quantity: 5
          eks_node_min_quantity: 1
          eks_node_disk_size: 20
          eks_node_instance_type: "m5.large"
      eks_node_spot: False
      eks_api_endpoint_private: False
      eks_secrets_envelope_encryption: True
  - name: eks-addons
    value:
      # Load balancing
      deploy_aws_lb_controller: True
      deploy_metrics_server: True
      deploy_nginx_controller:
        value: False
      deploy_external_dns: False
      # Storage drivers
      deploy_aws_ebs_csi: False
      deploy_aws_efs_csi: False
      # Autoscaling
      deploy_cluster_autoscaler: False
      # Secrets management
      deploy_secretsmanager_csi: False
      deploy_external_secrets: False
      # Monitoring/Logging/Tracing
      deploy_adot: True
      deploy_cloudwatch_container_insights_metrics: True
      deploy_cloudwatch_container_insights_logs: False
      cloudwatch_container_insights_logs_retention_days: 7
      deploy_amp: False
      deploy_grafana_for_amp: False
      # Reboot agent
      deploy_kured: False
      # Network level segmentation
      deploy_calico: False
      # Security policies
      deploy_kyverno:
        value: False
