name: examples
toolchainRegion: us-east-1
groups:
  - name: networking
    path: manifests/example/networking-modules.yaml
  - name: compute
    path: manifests/example/carlos-eks.yaml
#  - name: storage
#    path: manifests/example/storage-modules.yaml
targetAccountMappings:
  - alias: primary
    accountId:
      valueFrom:
        envVariable: PRIMARY_ACCOUNT
    default: true
    regionMappings:
      - region: us-east-1
        default: true

